# config for the detect run function
weights: C:\projets\yolov7\yolov7.pt # model.pt path(s)
#weights: C:\projets\external\database\airbus-aircraft-detection\data-2022-09-11\scratch\exp\weights\best.pt # model.pt path(s)
#source: C:\projets\external\database\isaid\data-2022-09-21\test\sample # file/dir/URL/glob, 0 for webcam
source: "0" # file/dir/URL/glob, 0 for webcam
img-size: "640" # inference  # DEFAULT = 640
conf-thres: "0.25"  # confidence threshold DEFAULT=0.25
iou-thres: "0.45"  # NMS IOU threshold DEFAULT=0.45
device: "0"
view-img: False  # show results DEFAULT=False
save-txt: True  # save results to *.txt DEFAULT=False
save-conf: False  # save confidences in --save-txt labels DEFAULT=False
nosave: False  # do not save images/videos DEFAULT=False
classes: None  # filter by class: --class 0, or --class 0 2 3 DEFAULT=None
agnostic-nms: False  # class-agnostic NMS DEFAULT=False
augment: False  # augmented inference DEFAULT=False
update: False  # update all models DEFAULT=False
project: C:\projets\external\database\isaid\data-2022-09-21\pretrained\sample-2022-09-22\ # save results to project/name
name: exp  # save results to project/name DEFAULT=exp
exist-ok: False # existing project/name ok, do not increment DEFAULT=False
vid-stride: "1"  # video frame-rate stride DEFAULT=1
no-trace: False # DEFAULT=False